Feature/description query
CSCfi/bp-network-ui pull request #50
Opened 2023-04-06 07:35 UTC by ViMuilu

### Description

Fixes dataset description search

### Related issues

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update (this needs a follow up PR)

### Changes Made

Added description search, added truncated description and removed beacon list from front page.

### Testing

- [ ] Unit Tests
- [ ] Integration Tests
- [ ] Tests do not apply
- [ ] Needs testing (start an issue or do a follow up PR about it)

### Mentions

2023-04-13 09:50 UTC, ViMuilu commented
There are no e2e tests for bp beacon so failing test build shouldn't matter

2023-04-17 11:34 UTC, sampsapenna requested changes

2023-04-17 11:34 UTC, sampsapenna commented on src/components/ImagingSearch.vue
> +
```suggestion
```

Empty line causing linter (`prettier`) to complain about style. Ditch the line to get e2e tests running again.

2023-04-17 11:34 UTC, sampsapenna commented on src/components/ImagingSearch.vue
> +
![Screenshot from 2023-04-17 14-33-55](https://user-images.githubusercontent.com/24293337/232472755-1e8f2209-3fde-4636-960e-d036c37b2420.png)

2023-04-17 11:52 UTC, sampsapenna approved these changes

2023-04-17 11:54 UTC, merged